//
//  ReferenceTableController.m
//  ThinkingGoneWrong
//
//  Created by Kevin Akers on 12/27/13.
//  Copyright (c) 2013 Polemics Applications. All rights reserved.
//

#import "ReferenceTableController.h"
#import "ReferenceReceiver.h"

@interface ReferenceTableController ()

@end

@implementation ReferenceTableController

- (id)initWithStyle:(UITableViewStyle)style
{
    self = [super initWithStyle:style];
    if (self) {
        // Custom initialization
    }
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];

    self.navigationItem.title = self.theTitle;   //set top title
    
    self.arrayTerms = [NSArray arrayWithObjects:
                  
                  //FORMAL FALLACIES
                  [NSArray arrayWithObjects:@"Affirmative conclusion from a negative premise",
                  @"Affirming the consequent",
                  @"Affirming a disjunct",
                  @"Appeal to probability",
                  @"Argument from fallacy",
                  @"Base Rate fallacy",
                  @"Conjunction fallacy",
                  @"Denying the antecedent",
                  @"Existential fallacy",
                  @"Fallacy of exclusive premises",
                  @"Fallacy of four terms",
                  @"Fallacy of the undistributed middle",
                  @"Illicit major",
                  @"Illicit minor",
                  @"Masked man fallacy",
                  @"Negative conclusion from affirmative premises", nil],
                       
                  //INFORMAL FALLACIES
                  [NSArray arrayWithObjects:@"Accident",
                        @"Abusive fallacy",
                        @"Ad hominem ",
                        @"Ambiguous middle term",
                        @"Appeal to accomplishment",
                        @"Appeal to authority",
                        @"Appeal to common sense",
                        @"Appeal to consequences",
                        @"Appeal to emotion",
                        @"Appeal to equality",
                        @"Appeal to motive",
                        @"Appeal to nature",
                        @"Appeal to novelty",
                        @"Appeal to poverty",
                        @"Appeal to tradition",
                        @"Appeal to wealth",
                        @"Argument from ignorance",
                        @"Argument from repetition",
                        @"Argument from silence",
                        @"Argument to moderation",
                        @"Argumentum ad baculum",
                        @"Argumentum ad hominem",
                        @"Argumentum ad populum",
                        @"Argumentum verbosium",
                        @"Association fallacy",
                        @"Bulverism",
                        @"Burden of proof",
                        @"Cherry picking",
                        @"Chronological snobbery",
                        @"Circular reasoning",
                        @"Circular cause and consequence",
                        @"Continuum fallacy",
                        @"Correlation proves causation",
                        @"Ecological fallacy",
                        @"Equivocation",
                        @"Etymological fallacy",
                        @"Fallacy of composition ",
                        @"Fallacy of division",
                        @"Fallacy of many questions",
                        @"Fallacy of quoting out of context",
                        @"Fallacy of relative privation",
                        @"Fallacy of the single cause",
                        @"False analogy",
                        @"False attribution",
                        @"False authority",
                        @"False dilemma",
                        @"Gambler's fallacy",
                        @"Genetic fallacy",
                        @"Hasty generalization",
                        @"Hedging",
                        @"Historian's fallacy",
                        @"Homunculus fallacy",
                        @"If-by-whiskey",
                        @"Ignoratio elenchi",
                        @"Incomplete comparison",
                        @"Inconsistent comparison",
                        @"Inductive fallacy",
                        @"Inflation of conflict",
                        @"Judgmental language",
                        @"Kettle logic",
                        @"Ludic fallacy",
                        @"Mind projection fallacy",
                        @"Misleading vividness",
                        @"Moralistic fallacy",
                        @"Moral high ground fallacy",
                        @"Moving the goalposts",
                        @"Naturalistic fallacy",
                        @"Naturalistic fallacy fallacy",
                        @"Nirvana fallacy",
                        @"No true Scotsman",
                        @"Onus probandi",
                        @"Overwhelming exception",
                        @"Pathetic fallacy",
                        @"Petitio principii ",
                        @"Poisoning the well",
                        @"Post hoc ergo propter hoc",
                        @"Proof by verbosity",
                        @"Prosecutor's fallacy",
                        @"Psychologist's fallacy",
                        @"Red herring",
                        @"Reductio ad Hitlerum",
                        @"Referential fallacy",
                        @"Regression fallacy",
                        @"Reification",
                        @"Retrospective determinism",
                        @"Shotgun argumentation",
                        @"Special pleading",
                        @"Straw man",
                        @"Suppressed correlative",
                        @"Texas sharpshooter fallacy",
                        @"Thought-terminating cliché",
                        @"Tu quoque",
                        @"Two wrongs make a right",
                        @"Wishful thinking",
                        @"Wrong direction", nil],
                       
//DECISION MAKING / BELIEF BIASES
                       [NSArray arrayWithObjects:@"Ambiguity effect",
                        @"Anchoring or focalism",
                        @"Attentional bias",
                        @"Availability heuristic",
                        @"Availability cascade",
                        @"Backfire effect",
                        @"Bandwagon effect",
                        @"Base rate fallacy or base rate neglect",
                        @"Belief bias",
                        @"Bias blind spot",
                        @"Cheerleader effect",
                        @"Choice-supportive bias",
                        @"Clustering illusion",
                        @"Confirmation bias",
                        @"Congruence bias",
                        @"Conjunction fallacy",
                        @"Conservatism or regressive bias",
                        @"Conservatism (Bayesian)",
                        @"Contrast effect",
                        @"Curse of knowledge",
                        @"Decoy effect",
                        @"Denomination effect",
                        @"Distinction bias",
                        @"Duration neglect",
                        @"Empathy gap",
                        @"Endowment effect",
                        @"Exaggerated expectation",
                        @"Experimenter's or expectation bias",
                        @"Functional fixedness",
                        @"Focusing effect",
                        @"Forer effect or Barnum effect",
                        @"Framing effect",
                        @"Frequency illusion",
                        @"Gambler's fallacy",
                        @"Hard-easy effect",
                        @"Hindsight bias",
                        @"Hostile media effect",
                        @"Hot-hand fallacy",
                        @"Hyperbolic discounting",
                        @"Identifiable victim effect",
                        @"Illusion of control",
                        @"Illusion of validity",
                        @"Illusory correlation",
                        @"IKEA effect",
                        @"Impact bias",
                        @"Information bias",
                        @"Insensitivity to sample size",
                        @"Irrational escalation",
                        @"Just-world hypothesis",
                        @"Less-is-better effect",
                        @"Loss aversion",
                        @"Ludic fallacy",
                        @"Mere exposure effect",
                        @"Money illusion",
                        @"Moral credential effect",
                        @"Negativity effect",
                        @"Negativity bias",
                        @"Neglect of probability",
                        @"Normalcy bias",
                        @"Observation selection bias",
                        @"Observer-expectancy effect",
                        @"Omission bias",
                        @"Optimism bias",
                        @"Ostrich effect",
                        @"Outcome bias",
                        @"Overconfidence effect",
                        @"Pareidolia",
                        @"Pessimism bias",
                        @"Planning fallacy",
                        @"Post-purchase rationalization",
                        @"Pro-innovation bias",
                        @"Pseudocertainty effect",
                        @"Reactance",
                        @"Reactive devaluation",
                        @"Recency illusion",
                        @"Restraint bias",
                        @"Rhyme as reason effect",
                        @"Risk compensation / Peltzman effect",
                        @"Selective perception",
                        @"Semmelweis reflex",
                        @"Social comparison bias",
                        @"Social desirability bias",
                        @"Status quo bias",
                        @"Stereotyping",
                        @"Subadditivity effect",
                        @"Subjective validation",
                        @"Survivorship bias",
                        @"Time-saving bias",
                        @"Unit bias",
                        @"Well travelled road effect",
                        @"Zero-risk bias",
                        @"Zero-sum heuristic", nil],
                       
                       //SOCIAL AND ATTRIBUTIONAL BIASES
                       [NSArray arrayWithObjects:
                        @"Actor-observer bias",
                        @"Defensive attribution hypothesis",
                        @"Dunning–Kruger effect",
                        @"Egocentric bias",
                        @"Extrinsic incentives bias",
                        @"False consensus effect",
                        @"Forer effect (aka Barnum effect)",
                        @"Fundamental attribution error",
                        @"Group attribution error",
                        @"Halo effect",
                        @"Illusion of asymmetric insight",
                        @"Illusion of external agency",
                        @"Illusion of transparency",
                        @"Illusory superiority",
                        @"Ingroup bias",
                        @"Just-world phenomenon",
                        @"Moral luck",
                        @"Naive cynicism",
                        @"Outgroup homogeneity bias",
                        @"Projection bias",
                        @"Self-serving bias",
                        @"Shared information bias",
                        @"System justification",
                        @"Trait ascription bias",
                        @"Ultimate attribution error",
                        @"Worse-than-average effect", nil],
                       
                       //MEMORY RELATED
                       [NSArray arrayWithObjects:
                        @"Bizarreness effect",
                        @"Choice-supportive bias",
                        @"Change bias",
                        @"Childhood amnesia",
                        @"Conservatism or Regressive Bias",
                        @"Consistency bias",
                        @"Context effect",
                        @"Cross-race effect",
                        @"Cryptomnesia",
                        @"Egocentric bias",
                        @"Fading affect bias",
                        @"False memory",
                        @"Generation effect (Self-generation effect)",
                        @"Google effect",
                        @"Hindsight bias",
                        @"Humor effect",
                        @"Illusion of truth effect",
                        @"Illusory correlation",
                        @"Leveling and Sharpening",
                        @"Levels-of-processing effect",
                        @"List-length effect",
                        @"Misinformation effect",
                        @"Modality effect",
                        @"Mood-congruent memory bias",
                        @"Next-in-line effect",
                        @"Part-list cueing effect",
                        @"Peak-end rule",
                        @"Persistence",
                        @"Picture superiority effect",
                        @"Positivity effect",
                        @"Primacy effect, Recency effect & Serial position effect",
                        @"Processing difficulty effect",
                        @"Reminiscence bump",
                        @"Rosy retrospection",
                        @"Self-relevance effect",
                        @"Source confusion",
                        @"Spacing effect",
                        @"Stereotypical bias",
                        @"Suffix effect",
                        @"Suggestibility",
                        @"Telescoping effect",
                        @"Testing effect",
                        @"Tip of the tongue phenomenon",
                        @"Verbatim effect",
                        @"Von Restorff effect",
                        @"Zeigarnik effect", nil],

                  
                  nil];
    
    self.arrayDefinitions = [NSArray arrayWithObjects:
                        
                        //FORMAL FALLACIES
                        [NSArray arrayWithObjects:@"(illicit negative) – when a categorical syllogism has a positive conclusion, but at least one negative premise.",
                         @"the antecedent in an indicative conditional is claimed to be true because the consequent is true; if A, then B; B, therefore A.",
                         @"concluded that one disjunct of a logical disjunction must be false because the other disjunct is true; A or B; A; therefore not B.",
                         @"takes something for granted because it would probably be the case (or might be the case).",
                         @"assumes that if an argument for some conclusion is fallacious, then the conclusion itself is false.",
                         @"making a probability judgement based on conditional probabilities, without taking into account the effect of prior probabilities.",
                         @"assumption that an outcome simultaneously satisfying multiple conditions is more probable than an outcome satisfying a single one of them.",
                         @"the consequent in an indicative conditional is claimed to be false because the antecedent is false; if A, then B; not A, therefore not B.",
                         @"an argument has a universal premise and a particular conclusion.",
                         @"a categorical syllogism that is invalid because both of its premises are negative.",
                         @"(quaternio terminorum) – a categorical syllogism that has four terms.",
                         @"the middle term in a categorical syllogism is not distributed.",
                         @"a categorical syllogism that is invalid because its major term is not distributed in the major premise but distributed in the conclusion.",
                         @"a categorical syllogism that is invalid because its minor term is not distributed in the minor premise but distributed in the conclusion.",
                         @"(illicit substitution of identicals) – the substitution of identical designators in a true statement can lead to a false one.",
                         @"(illicit affirmative) – when a categorical syllogism has a negative conclusion but affirmative premises. ", nil],
                             
                         //INFORMAL FALLACIES
                             [NSArray arrayWithObjects:
                              @"an exception to a generalization is ignored.",
                              @"a subtype of 'ad hominem' when it turns into verbal abuse of the opponent rather than arguing about the originally proposed argument.",
                              @"attacking the arguer instead of the argument.",
                              @"a common ambiguity in syllogisms in which the middle term is equivocated.",
                              @"where an assertion is deemed true or false based on the accomplishments of the proposer.",
                              @"(argumentum ab auctoritate) – where an assertion is deemed true because of the position or authority of the person asserting it.",
                              @"(argument from personal incredulity, divine fallacy) - I cannot imagine how this could be true, therefore it must be false.",
                              @"(argumentum ad consequentiam) – the conclusion is supported by a premise that asserts positive or negative consequences from some course of action in an attempt to distract from the initial discussion.",
                              @"where an argument is made due to the manipulation of emotions, rather than the use of valid reasoning.",
                              @"where an assertion is deemed true or false based on an assumed pretense of equality.",
                              @"where a premise is dismissed by calling into question the motives of its proposer.",
                              @"attempts to prove a claim about ethics by appealing to a definition of the term 'good' in terms of either one or more claims about natural properties.  Judgment is based solely on whether the subject of judgment is 'natural' or 'unnatural'.",
                              @"(argumentum novitatis/antiquitatis) – where a proposal is claimed to be superior or better solely because it is new or modern.",
                              @"(argumentum ad Lazarum) – supporting a conclusion because the arguer is poor (or refuting because the arguer is wealthy). (Opposite of appeal to wealth.)",
                              @"(argumentum ad antiquitam) – a conclusion supported solely because it has long been held to be true.",
                              @"(argumentum ad crumenam) – supporting a conclusion because the arguer is wealthy (or refuting because the arguer is poor).  (Sometimes taken together with the appeal to poverty as a general appeal to the arguer's financial situation.)",
                              @"(appeal to ignorance, argumentum ad ignorantiam) – assuming that a claim is true (or false) because it has not been proven false (true) or cannot be proven false (true).",
                              @"(argumentum ad nauseam) – signifies that it has been discussed extensively until nobody cares to discuss it anymore.",
                              @"(argumentum e silentio) – where the conclusion is based on the absence of evidence, rather than the existence of evidence.",
                              @"(false compromise, middle ground, fallacy of the mean) – assuming that the compromise between two positions is always correct.",
                              @"(appeal to the stick, appeal to force, appeal to threat) – an argument made through coercion or threats of force to support position.",
                              @"the evasion of the actual topic by directing the attack at your opponent.",
                              @"(appeal to widespread belief, bandwagon argument, appeal to the majority, appeal to the people) – where a proposition is claimed to be true or good solely because many people believe it to be so.",
                              @"(proof by verbosity, proof by intimidation) – submission of others to an argument too complex and verbose to reasonably deal with in all its intimate details.",
                              @"(guilt by association) – arguing that because two things share a property they are the same.",
                              @"(Psychogenetic Fallacy) inferring why an argument is being used, associating it to some psychological reason, then assuming it is invalid as a result. It is wrong to assume that if the origin of an idea comes from a biased mind, then the idea itself must also be a false.",
                              @"(see – onus probandi) (shifting the burden of proof) – I need not prove my claim, you must prove it is false.",
                              @"(suppressed evidence, incomplete evidence) – act of pointing at individual cases or data that seem to confirm a particular position, while ignoring a significant portion of related cases or data that may contradict that position.",
                              @"where a thesis is deemed incorrect because it was commonly held when something else, clearly false, was also commonly held.",
                              @"(circulus in demonstrando) – when the reasoner begins with what he or she is trying to end up with; sometimes called assuming the conclusion.",
                              @"where the consequence of the phenomenon is claimed to be its root cause.",
                              @"(fallacy of the beard, line-drawing fallacy, sorites fallacy, fallacy of the heap, bald man fallacy) – improperly rejecting a claim for being imprecise.",
                              @"(cum hoc ergo propter hoc) – a faulty assumption that correlation between two variables implies that one causes the other.",
                              @"inferences about the nature of specific individuals are based solely upon aggregate statistics collected for the group to which those individuals belong.",
                              @"the misleading use of a term with more than one meaning (by glossing over which meaning is intended at a particular time).",
                              @"which reasons that the original or historical meaning of a word or phrase is necessarily similar to its actual present-day meaning.",
                              @"assuming that something true of part of a whole must also be true of the whole.",
                              @"assuming that something true of a thing must also be true of all or some of its parts.",
                              @"(complex question, fallacy of presupposition, loaded question, plurium interrogationum) – someone asks a question that presupposes something that has not been proven or accepted by all the people involved. This fallacy is often used rhetorically, so that the question limits direct replies to those that serve the questioner's agenda.",
                              @"(contextomy) – refers to the selective excerpting of words from their original context in a way that distorts the source's intended meaning.",
                              @"dismissing an argument due to the existence of more important, but unrelated, problems in the world.",
                              @"(causal oversimplification) – it is assumed that there is one, simple cause of an outcome when in reality it may have been caused by a number of only jointly sufficient causes.",
                              @"an argument by analogy in which the analogy is poorly suited.",
                              @"an advocate appeals to an irrelevant, unqualified, unidentified, biased or fabricated source in support of an argument.",
                              @"(single authority) – using an expert of dubious credentials and/or using only one opinion to sell a product or idea. Related to the appeal to authority fallacy.",
                              @"(false dichotomy, fallacy of bifurcation, black-or-white fallacy) – two alternative statements are held to be the only possible options, when in reality there are more.",
                              @"the incorrect belief that separate, independent events can affect the likelihood of another random event. If a coin flip lands on heads 10 times in a row, the belief that it is 'due to the number of times it had previously landed on tails' is incorrect.",
                              @"where a conclusion is suggested based solely on something or someone's origin rather than its current meaning or context.",
                              @"(fallacy of insufficient statistics, fallacy of insufficient sample, fallacy of the lonely fact, leaping to a conclusion, hasty induction, secundum quid, converse accident) – basing a broad conclusion on a small sample.",
                              @"using words with ambiguous meanings, then changing the meaning of them later.",
                              @"occurs when one assumes that decision makers of the past viewed events from the same perspective and having the same information as those subsequently analyzing the decision. (Not to be confused with presentism, which is a mode of historical analysis in which present-day ideas, such as moral standards, are projected into the past.)",
                              @" where a 'middle-man' is used for explanation, this sometimes leads to regressive middle-men. Explains without actually explaining the real nature of a function or a process. Instead, it explains the concept in terms of the concept itself, without first defining or explaining the original concept. Explaining thought as something produced by a little thinker, a sort of homunculus inside the head, merely explains it as another kind of thinking (as different but the same).",
                              @"an argument that supports both sides of an issue by using terms that are selectively emotionally sensitive.",
                              @"(irrelevant conclusion, missing the point) – an argument that may in itself be valid, but does not address the issue in question.",
                              @"in which insufficient information is provided to make a complete comparison.",
                              @"where different methods of comparison are used, leaving one with a false impression of the whole comparison.",
                              @"A more general name to some fallacies, such as hasty generalization. It happens when a conclusion is made of premises which lightly supports it.",
                              @"The experts of a field of knowledge disagree on a certain point, so the scholars must know nothing, and therefore the legitimacy of their entire field is put to question.",
                              @"insulting or pejorative language to influence the recipient's judgment.",
                              @"using multiple inconsistent arguments to defend a position.",
                              @"the belief that the outcomes of non-regulated random occurrences can be encapsulated by a statistic; a failure to take into account unknown unknowns in determining the probability of events taking place.",
                              @"when one considers the way one sees the world as the way the world really is.",
                              @"involves describing an occurrence in vivid detail, even if it is an exceptional occurrence, to convince someone that it is a problem.",
                              @"inferring factual conclusions from purely evaluative premises in violation of fact–value distinction. For instance, inferring is from ought is an instance of moralistic fallacy. Moralistic fallacy is the inverse of naturalistic fallacy.",
                              @"in which one assumes a 'holier-than-thou' attitude in an attempt to make oneself look good to win an argument.",
                              @"(raising the bar) – argument in which evidence presented in response to a specific claim is dismissed and some other (often greater) evidence is demanded.",
                              @"inferring evaluative conclusions from purely factual premises in violation of fact–value distinction.  The inverse of morallistic fallacy.",
                              @"(anti-naturalistic fallacy) – inferring impossibility to infer any instance of ought from is from the general invalidity of is-ought fallacy.  An example of argument from fallacy.",
                              @"(perfect solution fallacy) – when solutions to problems are rejected because they are not perfect.",
                              @"when a generalization is made true only when a counterexample is ruled out on shaky grounds.",
                              @"from Latin onus probandi incumbit ei qui dicit, non ei qui negat the burden of proof is on the person who makes the claim, not on the person who denies (or questions the claim). It is a particular case of the 'argumentum ad ignorantiam' fallacy, here the burden is shifted on the person defending against the assertion.",
                              @"an accurate generalization that comes with qualifications which eliminate so many cases that what remains is much less impressive than the initial statement might have led one to assume.",
                              @" when an inanimate object is declared to have characteristics of animate objects.",
                              @"providing what is essentially the conclusion of the argument as a premise.",
                              @"a type of ad hominem where adverse information about a target is presented with the intention of discrediting everything that the target person says.",
                              @"Latin for 'after this, therefore because of this' (faulty cause/effect, coincidental correlation, correlation without causation) – X happened then Y happened; therefore X caused Y. The Loch Ness Monster has been seen in this loch. Something tipped our boat over; it's obviously the Loch Ness Monster.",
                              @"(argumentum verbosium, proof by intimidation) – submission of others to an argument too complex and verbose to reasonably deal with in all its intimate details.",
                              @"a low probability of false matches does not mean a low probability of some false match being found.",
                              @"an observer presupposes the objectivity of his own perspective when analyzing a behavioral event.",
                              @"a speaker attempts to distract an audience by deviating from the topic at hand by introducing a separate argument which the speaker believes will be easier to speak to.",
                              @"(playing the Nazi card) – comparing an opponent or their argument to Hitler or Nazism in an attempt to associate a position with one that is universally reviled.",
                              @"assuming all words refer to existing things and that the meaning of words reside within the things they refer to, as opposed to words possibly referring no real object or that the meaning of words often comes from how we use them.",
                              @"ascribes cause where none exists. The flaw is failing to account for natural fluctuations. It is frequently a special kind of the post hoc fallacy.",
                              @"(hypostatization) – a fallacy of ambiguity, when an abstraction (abstract belief or hypothetical construct) is treated as if it were a concrete, real event or physical entity. In other words, it is the error of treating as a 'real thing' something which is not a real thing, but merely an idea.",
                              @"the argument that because some event has occurred, its occurrence must have been inevitable beforehand.",
                              @"the arguer offers such a large number of arguments for their position that the opponent can't possibly respond to all of them.",
                              @"where a proponent of a position attempts to cite something as an exemption to a generally accepted rule or principle without justifying the exemption.",
                              @"an argument based on misrepresentation of an opponent's position.",
                              @"where a correlative is redefined so that one alternative is made impossible.",
                              @"improperly asserting a cause to explain a cluster of data.",
                              @"a commonly used phrase, sometimes passing as folk wisdom, used to quell cognitive dissonance, conceal lack of thought-entertainment, move onto other topics etc. but in any case, end the debate with a cliche—not a point.",
                              @"('you too', appeal to hypocrisy, I'm rubber and you're glue) – the argument states that a certain position is false or wrong and/or should be disregarded because its proponent fails to act consistently in accordance with that position.",
                              @"occurs when it is assumed that if one wrong is committed, another wrong will cancel it out.",
                              @"a specific type of appeal to emotion where a decision is made according to what might be pleasing to imagine, rather than according to evidence or reason.",
                              @"cause and effect are reversed. The cause is said to be the effect and vice versa.", nil],
                             
                        //DECISION MAKING / BELIEF BIASES
                             [NSArray arrayWithObjects:@"The tendency to avoid options for which missing information makes the probability seem 'unknown.'",
                              @"The tendency to rely too heavily, or 'anchor,' on one trait or piece of information when making decisions.",
                              @"The tendency of our perception to be affected by our recurring thoughts. ",
                              @"The tendency to overestimate the likelihood of events with greater 'availability' in memory, which can be influenced by how recent the memories are or how unusual or emotionally charged they may be.",
                              @"A self-reinforcing process in which a collective belief gains more and more plausibility through its increasing repetition in public discourse (or 'repeat something long enough and it will become true').",
                              @"When people react to disconfirming evidence by strengthening their beliefs.",
                              @"The tendency to do (or believe) things because many other people do (or believe) the same. Related to groupthink and herd behavior.",
                              @"The tendency to ignore base rate information (generic, general information) and focus on specific information (information only pertaining to a certain case).",
                              @"An effect where someone's evaluation of the logical strength of an argument is biased by the believability of the conclusion.",
                              @"The tendency to see oneself as less biased than other people, or to be able to identify more cognitive biases in others than in oneself.",
                              @"The tendency for people to appear more attractive in a group than in isolation.",
                              @"The tendency to remember one's choices as better than they actually were.",
                              @"The tendency to over-expect small runs, streaks, or clusters in large samples of random data (that is, seeing phantom patterns).",
                              @"The tendency to search for, interpret, focus on and remember information in a way that confirms one's preconceptions.",
                              @"The tendency to test hypotheses exclusively through direct testing, instead of testing possible alternative hypotheses.",
                              @"The tendency to assume that specific conditions are more probable than general ones.",
                              @"A certain state of mind wherein high values and high likelihoods are overestimated while low values and low likelihoods are underestimated.",
                              @"The tendency to insufficiently revise one's belief when presented with new evidence.",
                              @"The enhancement or reduction of a certain perception's stimuli when compared with a recently observed, contrasting object.",
                              @"When better-informed people find it extremely difficult to think about problems from the perspective of lesser-informed people.",
                              @"Preferences for either option A or B changes in favor of option B when option C is presented, which is similar to option B but in no way better.",
                              @"The tendency to spend more money when it is denominated in small amounts (e.g. coins) rather than large amounts (e.g. bills).",
                              @"The tendency to view two options as more dissimilar when evaluating them simultaneously than when evaluating them separately.",
                              @"The neglect of the duration of an episode in determining its value",
                              @"The tendency to underestimate the influence or strength of feelings, in either oneself or others.",
                              @"The fact that people often demand much more to give up an object than they would be willing to pay to acquire it.",
                              @"Based on the estimates, real-world evidence turns out to be less extreme than our expectations (conditionally inverse of the conservatism bias).",
                              @"The tendency for experimenters to believe, certify, and publish data that agree with their expectations for the outcome of an experiment, and to disbelieve, discard, or downgrade the corresponding weightings for data that appear to conflict with those expectations.",
                              @"Limits a person to using an object only in the way it is traditionally used.",
                              @"The tendency to place too much importance on one aspect of an event.",
                              @"The observation that individuals will give high accuracy ratings to descriptions of their personality that supposedly are tailored specifically for them, but are in fact vague and general enough to apply to a wide range of people. This effect can provide a partial explanation for the widespread acceptance of some beliefs and practices, such as astrology, fortune telling, graphology, and some types of personality tests.",
                              @"Drawing different conclusions from the same information, depending on how or by whom that information is presented.",
                              @"The illusion in which a word, a name or other thing that has recently come to one's attention suddenly seems to appear with improbable frequency shortly afterwards (see also recency illusion).",
                              @"The tendency to think that future probabilities are altered by past events, when in reality they are unchanged. Results from an erroneous conceptualization of the law of large numbers. For example, 'I've flipped heads with this coin five times consecutively, so the chance of tails coming out on the sixth flip is much greater than heads.'",
                              @"Based on a specific level of task difficulty, the confidence in judgments is too conservative and not extreme enough",
                              @"Sometimes called the 'I-knew-it-all-along' effect, the tendency to see past events as being predictable at the time those events happened.",
                              @"The tendency to see a media report as being biased, owing to one's own strong partisan views.",
                              @"The 'hot-hand fallacy' (also known as the 'hot hand phenomenon' or 'hot hand') is the fallacious belief that a person who has experienced success has a greater chance of further success in additional attempts.",
                              @"The tendency for people to have a stronger preference for more immediate payoffs relative to later payoffs, where the tendency increases the closer to the present both payoffs are.  Also known as current moment bias, present-bias, and related to Dynamic inconsistency.",
                              @"The tendency to respond more strongly to a single identified person at risk than to a large group of people at risk.",
                              @"The tendency to overestimate one's degree of influence over other external events.",
                              @"Belief that additional acquired information generates additional relevant data for predictions, even when it evidently does not.",
                              @"Inaccurately perceiving a relationship between two unrelated events.",
                              @"The tendency for people to place a disproportionately high value on objects that they partially assembled themselves, such as furniture from IKEA, regardless of the quality of the end result.",
                              @"The tendency to overestimate the length or the intensity of the impact of future feeling states.",
                              @"The tendency to seek information even when it cannot affect action.",
                              @"The tendency to under-expect variation in small samples",
                              @"The phenomenon where people justify increased investment in a decision, based on the cumulative prior investment, despite new evidence suggesting that the decision was probably wrong.",
                              @"The tendency for people to want to believe that the world is fundamentally just, causing them to rationalize an otherwise inexplicable injustice as deserved by the victim(s).",
                              @"The tendency to prefer a smaller set to a larger set judged separately, but not jointly",
                              @"the disutility of giving up an object is greater than the utility associated with acquiring it.  (see also Sunk cost effects and endowment effect).",
                              @"The misuse of games to model real-life situations.",
                              @"The tendency to express undue liking for things merely because of familiarity with them.",
                              @"The tendency to concentrate on the nominal (face value) of money rather than its value in terms of purchasing power.",
                              @"The tendency of a track record of non-prejudice to increase subsequent prejudice.",
                              @"The tendency of people, when evaluating the causes of the behaviors of a person they dislike, to attribute their positive behaviors to the environment and their negative behaviors to the person's inherent nature or of young people to be more negative information in the descriptions of others",
                              @"Psychological phenomenon by which humans have a greater recall of unpleasant memories compared with positive memories.",
                              @"The tendency to completely disregard probability when making a decision under uncertainty.",
                              @"The refusal to plan for, or react to, a disaster which has never happened before.",
                              @"The effect of suddenly noticing things that were not noticed previously – and as a result wrongly assuming that the frequency has increased.",
                              @"When a researcher expects a given result and therefore unconsciously manipulates an experiment or misinterprets data in order to find it (see also subject-expectancy effect).",
                              @"The tendency to judge harmful actions as worse, or less moral, than equally harmful omissions (inactions).",
                              @"The tendency to be over-optimistic, overestimating favorable and pleasing outcomes (see also wishful thinking, valence effect, positive outcome bias).",
                              @"Ignoring an obvious (negative) situation.",
                              @"The tendency to judge a decision by its eventual outcome instead of based on the quality of the decision at the time it was made.",
                              @"Excessive confidence in one's own answers to questions.",
                              @"A vague and random stimulus (often an image or sound) is perceived as significant, e.g., seeing images of animals or faces in clouds, the man in the moon, and hearing non-existent hidden messages on records played in reverse.",
                              @"The tendency for some people, especially those suffering from depression, to overestimate the likelihood of negative things happening to them.",
                              @"The tendency to underestimate task-completion times.",
                              @"The tendency to persuade oneself through rational argument that a purchase was a good value.",
                              @"The tendency to have an excessive optimism towards an invention or innovation's usefulness throughout society, while often failing to identify its limitations and weaknesses.",
                              @"The tendency to make risk-averse choices if the expected outcome is positive, but make risk-seeking choices to avoid negative outcomes.",
                              @"The urge to do the opposite of what someone wants you to do out of a need to resist a perceived attempt to constrain your freedom of choice.",
                              @"Devaluing proposals only because they are purportedly originated with an adversary.",
                              @"The illusion that a word or language usage is a recent innovation when it is in fact long-established (see also frequency illusion).",
                              @"The tendency to overestimate one's ability to show restraint in the face of temptation.",
                              @"Rhyming statements are perceived as more truthful. A famous example being used in the O.J Simpson trial with the defense's use of the phrase 'If the gloves don't fit, then you must acquit.'",
                              @"The tendency to take greater risks when perceived safety increases.",
                              @"The tendency for expectations to affect perception.",
                              @"The tendency to reject new evidence that contradicts a paradigm.",
                              @"The tendency, when making hiring decisions, to favour potential candidates who don't compete with one's own particular strengths.",
                              @"The tendency to over-report socially desirable characteristics or behaviours in one self and under-report socially undesirable characteristics or behaviours.",
                              @"The tendency to like things to stay relatively the same (see also loss aversion, endowment effect, and system justification).",
                              @"Expecting a member of a group to have certain characteristics without having actual information about that individual.",
                              @"The tendency to judge probability of the whole to be less than the probabilities of the parts.",
                              @"Perception that something is true if a subject's belief demands it to be true. Also assigns perceived connections between coincidences.",
                              @"Concentrating on the people or things that 'survived' some process and inadvertently overlooking those that didn't because of their lack of visibility.",
                              @"Underestimations of the time that could be saved (or lost) when increasing (or decreasing) from a relatively low speed and overestimations of the time that could be saved (or lost) when increasing (or decreasing) from a relatively high speed.",
                              @"The tendency to want to finish a given unit of a task or an item. Strong effects on the consumption of food in particular.",
                              @"Underestimation of the duration taken to traverse oft-traveled routes and overestimation of the duration taken to traverse less familiar routes.",
                              @"Preference for reducing a small risk to zero over a greater reduction in a larger risk.",
                              @"Intuitively judging a situation to be zero-sum (i.e., that gains and losses are correlated). Derives from the zero-sum game in game theory, where wins and losses sum to zero.  The frequency with which this bias occurs may be related to the social dominance orientation personality factor.", nil],
                             
                        //SOCIAL BIASES
                        [NSArray arrayWithObjects:
                         @"The tendency for explanations of other individuals' behaviors to overemphasize the influence of their personality and underemphasize the influence of their situation (see also Fundamental attribution error), and for explanations of one's own behaviors to do the opposite (that is, to overemphasize the influence of our situation and underemphasize the influence of our own personality).",
                         @"Attributing more blame to a harm-doer as the outcome becomes more severe or as personal or situational similarity to the victim increases.",
                         @"An effect in which incompetent people fail to realise they are incompetent because they lack the skill to distinguish between competence and incompetence. Actual competence may weaken self-confidence, as competent individuals may falsely assume that others have an equivalent understanding.",
                         @"Occurs when people claim more responsibility for themselves for the results of a joint action than an outside observer would credit them.",
                         @"An exception to the fundamental attribution error, when people view others as having (situational) extrinsic motivations and (dispositional) intrinsic motivations for oneself",
                         @"The tendency for people to overestimate the degree to which others agree with them.",
                         @"The tendency to give high accuracy ratings to descriptions of their personality that supposedly are tailored specifically for them, but are in fact vague and general enough to apply to a wide range of people. For example, horoscopes.",
                         @"The tendency for people to over-emphasize personality-based explanations for behaviors observed in others while under-emphasizing the role and power of situational influences on the same behavior (see also actor-observer bias, group attribution error, positivity effect, and negativity effect).",
                         @"The biased belief that the characteristics of an individual group member are reflective of the group as a whole or the tendency to assume that group decision outcomes reflect the preferences of group members, even when information is available that clearly suggests otherwise.",
                         @"The tendency for a person's positive or negative traits to 'spill over' from one personality area to another in others' perceptions of them (see also physical attractiveness stereotype).",
                         @"People perceive their knowledge of their peers to surpass their peers' knowledge of them.",
                         @"When people view self-generated preferences as instead being caused by insightful, effective and benevolent agents",
                         @"People overestimate others' ability to know them, and they also overestimate their ability to know others.",
                         @"Overestimating one's desirable qualities, and underestimating undesirable qualities, relative to other people. (Also known as 'Lake Wobegon effect,' 'better-than-average effect,' or 'superiority bias').",
                         @"The tendency for people to give preferential treatment to others they perceive to be members of their own groups.",
                         @"The tendency for people to believe that the world is just and therefore people 'get what they deserve.'",
                         @"The tendency for people to ascribe greater or lesser moral standing based on the outcome of an event",
                         @"Expecting more egocentric bias in others than in oneself",
                         @"Individuals see members of their own group as being relatively more varied than members of other groups.",
                         @"The tendency to unconsciously assume that others (or one's future selves) share one's current emotional states, thoughts and values.",
                         @"The tendency to claim more responsibility for successes than failures. It may also manifest itself as a tendency for people to evaluate ambiguous information in a way beneficial to their interests (see also group-serving bias).",
                         @"Known as the tendency for group members to spend more time and energy discussing information that all members are already familiar with (i.e., shared information), and less time and energy discussing information that only some members are aware of (i.e., unshared information).",
                         @"The tendency to defend and bolster the status quo. Existing social, economic, and political arrangements tend to be preferred, and alternatives disparaged sometimes even at the expense of individual and collective self-interest.",
                         @"The tendency for people to view themselves as relatively variable in terms of personality, behavior, and mood while viewing others as much more predictable.",
                         @"Similar to the fundamental attribution error, in this error a person is likely to make an internal attribution to an entire group instead of the individuals within the group.",
                         @"A tendency to believe ourselves to be worse than others at tasks which are difficult.", nil],
                        
                        //MEMORY RELATED
                        [NSArray arrayWithObjects:
                         @"Bizarre material is better remembered than common material.",
                         @"In a self-justifying manner retroactively ascribing one's choices to be more informed than they were when they were made.",
                         @"After an investment of effort in producing change, remembering one's past performance as more difficult than it actually was.",
                         @"The retention of few memories from before the age of four.",
                         @"Tendency to remember high values and high likelihoods/probabilities/frequencies lower than they actually were and low ones higher than they actually were. ",
                         @"Incorrectly remembering one's past attitudes and behaviour as resembling present attitudes and behaviour.",
                         @"That cognition and memory are dependent on context, such that out-of-context memories are more difficult to retrieve than in-context memories (e.g., recall time and accuracy for a work-related memory will be lower at home, and vice versa)",
                         @"The tendency for people of one race to have difficulty identifying members of a race other than their own.",
                         @"A form of misattribution where a memory is mistaken for imagination, because there is no subjective experience of it being a memory.",
                         @"Recalling the past in a self-serving manner, e.g., remembering one's exam grades as being better than they were, or remembering a caught fish as bigger than it really was.",
                         @"A bias in which the emotion associated with unpleasant memories fades more quickly than the emotion associated with positive events.",
                         @"A form of misattribution where imagination is mistaken for a memory.",
                         @"That self-generated information is remembered best. For instance, people are better able to recall memories of statements that they have generated than similar statements generated by others.",
                         @"The tendency to forget information that can be found readily online by using Internet search engines .",
                         @"The inclination to see past events as being more predictable than they actually were; also called the 'I-knew-it-all-along' effect.",
                         @"That humorous items are more easily remembered than non-humorous ones, which might be explained by the distinctiveness of humor, the increased cognitive processing time to understand the humor, or the emotional arousal caused by the humor.",
                         @"That people are more likely to identify as true statements those they have previously heard (even if they cannot consciously remember having heard them), regardless of the actual validity of the statement. In other words, a person is more likely to believe a familiar statement than an unfamiliar one.",
                         @"Inaccurately remembering a relationship between two events.",
                         @"Memory distortions introduced by the loss of details in a recollection over time, often concurrent with sharpening or selective recollection of certain details that take on exaggerated significance in relation to the details or aspects of the experience lost through leveling. Both biases may be reinforced over time, and by repeated recollection or re-telling of a memory.",
                         @"That different methods of encoding information into memory have different levels of effectiveness.",
                         @"A smaller percentage of items are remembered in a longer list, but as the length of the list increases, the absolute number of items remembered increases as well.",
                         @"Memory becoming less accurate because of interference from post-event information.",
                         @"That memory recall is higher for the last items of a list when the list items were received via speech than when they were received through writing.",
                         @"The improved recall of information congruent with one's current mood.",
                         @"That a person in a group has diminished recall for the words of others who spoke immediately before himself, if they take turns speaking.",
                         @"That being shown some items from a list and later retrieve one item causes it to become harder to retrieve the other items",
                         @"That people seem to perceive not the sum of an experience but the average of how it was at its peak (e.g. pleasant or unpleasant) and how it ended.",
                         @"The unwanted recurrence of memories of a traumatic event.",
                         @"The notion that concepts that are learned by viewing pictures are more easily and frequently recalled than are concepts that are learned by viewing their written word form counterparts.",
                         @"That older adults favor positive over negative information in their memories.",
                         @"That items near the end of a sequence are the easiest to recall, followed by the items at the beginning of a sequence; items in the middle are the least likely to be remembered.",
                         @"That information which is read longer time and more thought about (more diffculty processed) is easier remembered.",
                         @"The recalling of more personal events from adolescence and early adulthood than personal events from other lifetime periods",
                         @"The remembering of the past as having been better than it really was.",
                         @"That memories relating to the self are better recalled than similar information relating to others.",
                         @"Confusing episodic memories with other information, creating distorted memories.",
                         @"(Lag Effect) That information is better recalled if exposure to it is repeated over a long span of time rather than a short one.",
                         @"Memory distorted towards stereotypes (e.g. racial or gender)",
                         @"Diminish of the recency effect  because  a sound item is appended to the list that the subject is not required to recall.",
                         @"A form of misattribution where ideas suggested by a questioner are mistaken for memory.",
                         @"The tendency to displace recent events backward in time and remote events forward in time, so that recent events appear more remote, and remote events, more recent.",
                         @"The fact that you easier remember information you have read by rewriting it instead of rereading it.",
                         @"When a subject is able to recall parts of an item, or related information, but is frustratingly unable to recall the whole item. This is thought an instance of 'blocking' where multiple similar memories are being recalled and interfere with each other.",
                         @"That the 'gist' of what someone has said is better remembered than the verbatim wording.  This is because memories are representations and not carbon copy clones.",
                         @"That an item that sticks out is more likely to be remembered than other items",
                         @"That uncompleted or interrupted tasks are remembered better than completed ones.",
nil],
                        
                        
                        nil];
    
    //SET WHICH ARRAY TO USE
    currentTermsArray = [self.arrayTerms objectAtIndex:self.passedNumber];
    currentDefinitionsArray = [self.arrayDefinitions objectAtIndex:self.passedNumber];
  
}


- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    
    NSIndexPath *myIndexPath = [self.tableView indexPathForSelectedRow];
    NSInteger row = myIndexPath.row;
    
    if ([segue.identifier isEqualToString:@"theSegue"]) {
        ReferenceReceiver *Vc2 = [segue destinationViewController];
        Vc2.theTitle = [currentTermsArray objectAtIndex:row];
        Vc2.theDefinition = [currentDefinitionsArray objectAtIndex:row];
    }
    
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    // Return the number of sections.
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return [currentTermsArray count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *CellIdentifier = @"Cell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];
    
    cell.textLabel.text = [currentTermsArray objectAtIndex:[indexPath row]];
    
    // Configure the cell...
    
    return cell;
}


@end
